### ISSUE TITLE
"IIIT Ranchi Hacktoberfest" logo and "Hacktoberfest 2019" logo overlap in mobile view on the "atendees" page

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#30]
"IIIT Ranchi Hacktoberfest" logo and "Hacktoberfest 2019" logo overlap in mobile view on the "atendees" page.

Please also check if it occurs on other pages. If you want to fix this issue comment first to get it assigned to you.

We will be guiding you, so don't worry if you have never fixed an issue before.

**Comment by Mahesh-Mavuri** [comment]
Can I work on this?
I have a small question. What needs to be done for IIIT Hacktober Fest text/ hyperlink in mobile screen???

**Comment by anktrj** [comment]
Hey, @Mahesh-Mavuri regarding your query, make the hyperlink text at the top and shift the other icon after that.
