### ISSUE TITLE
Add a animation like "baffleJs" or any other good animation to the text in yellow "IIIT Ranchi" in the atendees page

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#31]
Add a animation like "baffleJs" or any other good animation to the text in yellow "IIIT Ranchi" in the atendees page.

Search for animation and suggest in the comments, we will assign you if we like the animation. The libraries are available on the net...its a relatively simple task..but you are free even to do everything in vanilla js

we will guide you through the whole process, so, don't worry if this is your first issue.

**Comment by Sobanim** [comment]
Hello. Can I try do this issue? Maybe today or tomorrow?

**Comment by anktrj** [comment]
Hey, @Sobanim, I am assigning this Enhancement to you. Keep Contributing.

**Comment by Sobanim** [comment]
Also Can I add any other animation? and you can choose better animation

**Comment by anktrj** [comment]
Yup sure @Sobanim
