### ISSUE TITLE
Set the "HacktoberFest IIITR" link to "https://iiitranchi.github.io/hacktoberfest-19/"

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#34]
Set the "HacktoberFest IIITR" link to "https://iiitranchi.github.io/hacktoberfest-19/" in every subdomain.

Comment below if you think you can solve this issue, to get assigned.

Don't worry if this is your first issue. We will be helping you out throughout the process.

**Comment by SumeetHaryani** [comment]
@Vishal19111999 I would like to work on this issue.

**Comment by vishalvibes** [comment]
Go ahead @SumeetHaryani
