### ISSUE TITLE
Change the link of every "HacktoberFest 2019" logo to the official website of HacktoberFest

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#35]
Change the link of every "HacktoberFest 2019" logo to the official website of HacktoberFest in every subdomain of this project.

Comment below if you think you can solve this issue, to get assigned.

Don't worry if this is your first issue. We will be helping you out throughout the process.

**Comment by anktrj** [comment]
Closing this issue. Fixed by @mannypanwar
