### ISSUE TITLE
In the home page, in Events section, make the height of all 3 divs to be same

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#36]
In the home page, in Events section, make the height of all 3 <div>s to be same, no problem if there's some gap below the text.

If this is your first issue, feel free to ask questions, we would love to help you in this process

**Comment by SumeetHaryani** [comment]
@Vishal19111999  I would like to work on this issue.

**Comment by anktrj** [comment]
Go for it, I am assigning this issue to you.
