### ISSUE TITLE
"Events" link in the navbar of homepage isnot working

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#37]
"Events" link in the navbar of homepage is not working. Set its link to Events section of the homepage.

Fell free to take help from us if this is your first bug. Inform us before solving this bug, so that we can assign you.

**Comment by SumeetHaryani** [comment]
@Vishal19111999 I would like to work on this issue.

**Comment by anktrj** [comment]
@SumeetHaryani  Go for it. I am assigning this issue to you.

**Comment by anktrj** [comment]
Thanks @SumeetHaryani  Issue has been resolved.
