### ISSUE TITLE
Set the favicon of "https://iiitranchi.github.io/hacktoberfest-19/attendees/" to similar as that of hacktoberfest official website

### ISSUE THREAD

**Issue by vishalvibes** [iiitranchi/iiitranchi.github.io#38]
Set the favicon of "https://iiitranchi.github.io/hacktoberfest-19/attendees/" to similar as that of hacktoberfest official website

Comment below to reserve this bug, we will be happy to guide you if this  is your first bug.

**Comment by anktrj** [comment]
I have uploaded the image to be used for the favicon in hacktoberfest-19/attendees/assets/img/favicon.png
Anyone working in this issue can use the src for favicon.

**Comment by SumeetHaryani** [comment]
@ankiiitraj  and @Vishal19111999  I would like to work on this issue.

**Comment by anktrj** [comment]
Go for it. I will be assigning this issue too you.
