### ISSUE TITLE
Set the favicon for https://iiitranchi.github.io/hacktoberfest-19/attendees/ same as the official favicon of https://hacktoberfest.digitalocean.com

### ISSUE THREAD

**Issue by anktrj** [iiitranchi/iiitranchi.github.io#42]
The attendees page don't have any favicon.
You can find the favicon for this issue in "hacktoberfest-19/attendees/assets/img/favicon.png" .

**Comment by IsabelVazquez** [comment]
Hello - may I have this issue?

**Comment by anktrj** [comment]
Go for it. @IsabelVazquez Feel free to ask for assistance.

**Comment by anktrj** [comment]
Closing this issue. It has been resolved by @SumeetHaryani
