### ISSUE TITLE
The Cards on the homepage are very close to eachother.

### ISSUE THREAD

**Issue by anktrj** [iiitranchi/iiitranchi.github.io#46]
On page https://iiitranchi.github.io/hacktobefest-19 The Event card needs slight larger margin in Mobile device view only.
![Screenshot_20191007-183437](https://user-images.githubusercontent.com/48787278/66314393-80683f00-e903-11e9-980f-0cbac4ddd897.png)

**Comment by SumeetHaryani** [comment]
@ankiiitraj, I would like to work on this issue.

**Comment by anktrj** [comment]
@SumeetHaryani Go for it.
